"""change kit/sample relationship

Revision ID: 627766051333
Revises: 822dfb9decab
Create Date: 2021-07-09 11:12:28.764065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627766051333'
down_revision = '822dfb9decab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('samples_kit_id_fkey', 'samples', type_='foreignkey')
    op.create_foreign_key(None, 'samples', 'kits', ['kit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.create_foreign_key('samples_kit_id_fkey', 'samples', 'kits', ['kit_id'], ['id'])
    # ### end Alembic commands ###
